version: '2'

services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: javaee_user
      POSTGRES_PASSWORD: javaee_user
      POSTGRES_DB: javaee_db
